### ISSUE TITLE
Issues in rank operator

### ISSUE THREAD

**Issue by noahboerger** [Meaningful-Data/vtlengine#34]
When `ds1` is

| id_1       | id_2       | id_3      | val     | 
|------------|------------|---------|---------|
| IDENTIFIER | IDENTIFIER | IDENTIFIER | MEASURE| 
| INTEGER    | INTEGER    | INTEGER |  INTEGER|
| 1          | 1          | 1       |  1 |
| 1          | 1          | 2       |  1 |
| 1          | 2          | 1       |  1 |
| 2          | 1          | 1       |  1 |
| 2          | 2          | 1       |  1 |
| 2          | 2          | 2       |  1 |
| 3          | 1          | 1       |  1 |
| 3          | 2          | 1       |  1 |
| 3          | 2          | 2       |  1 |

The result of `ds2 := ds1[calc rank_col := rank(over(order by id_1))];` should be out of my point of view

| id_1       | id_2       | id_3      | val     | rank_col | 
|------------|------------|---------|---------|---------|
| IDENTIFIER | IDENTIFIER | IDENTIFIER | MEASURE | MEASURE | 
| INTEGER    | INTEGER    | INTEGER |  INTEGER | INTEGER |
| 1          | 1          | 1       |  1 | 1 |
| 1          | 1          | 2       |  1 | 1 |
| 1          | 2          | 1       |  1 | 1 |
| 2          | 1          | 1       |  1 |  4 |
| 2          | 2          | 1       |  1 |  4 |
| 2          | 2          | 2       |  1 | 4 |
| 3          | 1          | 1       |  1 | 7 |
| 3          | 2          | 1       |  1 | 7 |
| 3          | 2          | 2       |  1 | 7 |

but currently is 

| id_1       | id_2       | id_3      | val     | rank_col | 
|------------|------------|---------|---------|---------|
| IDENTIFIER | IDENTIFIER | IDENTIFIER | MEASURE | MEASURE | 
| INTEGER    | INTEGER    | INTEGER |  INTEGER | INTEGER |
| 1          | 1          | 1       |  1 | 1 |
| 1          | 1          | 2       |  1 | 1 |
| 1          | 2          | 1       |  1 | 1 |
| 2          | 1          | 1       |  1 |  2 |
| 2          | 2          | 1       |  1 |  2 |
| 2          | 2          | 2       |  1 | 1 |
| 3          | 1          | 1       |  1 | 3 |
| 3          | 2          | 1       |  1 | 3 |
| 3          | 2          | 2       |  1 | 2 |

**Comment by antonio-olleros** [comment]
Thanks a lot, @noahboerger , for spotting this. I agree with you , the manual says explicitly:

 If some Data Points are in the same order according to the specified orderClause, the same order number (rank) is assigned and a gap appears in the sequence of the assigned ranks (for example, if four Data Points have the same rank 5, the following assigned rank would be 9).

We'll fix it

**Comment by noahboerger** [comment]
Thank you! Maybe you could also take a look in an execution of rank on an dataset without measures.

The same operation e.g. on 
| id_1       | id_2       | id_3      | 
|------------|------------|---------|
| IDENTIFIER | IDENTIFIER | IDENTIFIER |
| INTEGER    | INTEGER    | INTEGER |
| 1          | 1          | 1       |  
| 1          | 1          | 2       |  
| 1          | 2          | 1       | 
| 2          | 1          | 1       |  
| 2          | 2          | 1       |  
| 2          | 2          | 2       |  
| 3          | 1          | 1       |  
| 3          | 2          | 1       |  
| 3          | 2          | 2       |  

Currently throws in my execution the following exception:

<details>
  <summary>Occured error</summary>

  ### Exception
  ```
".../venv/lib/python3.10/site-packages/vtlengine/Interpreter/__init__.py", line 513, in visit_Analytic
    measure_name = result.get_measures_names()[0]
IndexError: list index out of range
  ```
</details>

**Comment by javihern98** [comment]
> Thank you! Maybe you could also take a look in an execution of rank on an dataset without measures.
> 
> The same operation e.g. on
> id_1 	id_2 	id_3
> IDENTIFIER 	IDENTIFIER 	IDENTIFIER
> INTEGER 	INTEGER 	INTEGER
> 1 	1 	1
> 1 	1 	2
> 1 	2 	1
> 2 	1 	1
> 2 	2 	1
> 2 	2 	2
> 3 	1 	1
> 3 	2 	1
> 3 	2 	2
> 
> Currently throws in my execution the following exception:
> Occured error
> ### Exception
> 
> ```
> ".../venv/lib/python3.10/site-packages/vtlengine/Interpreter/__init__.py", line 513, in visit_Analytic
>   measure_name = result.get_measures_names()[0]
> IndexError: list index out of range
> ```

Seems to be an unhandled exception, need to check:
- If analytic can be used without any measure
- If so, then handle properly this use case

**Comment by javihern98** [comment]
Current implementation is based on duck_db. Docs show this for the different rank functions:

![image](https://github.com/user-attachments/assets/b4acd57c-f33f-4d86-b0b8-bd82e64b6e49)
![image](https://github.com/user-attachments/assets/0b2c68ee-fc77-4cfb-aa00-9b488ec2b62e)

We currently use "rank()" function, which following the documentation should be the same as the VTL language. It seems there is an internal bug on duckdb that enforces the behaviour of dense_rank(), which creates the discrepancy with the VTL Reference Manual.

Proposed actions:
- Raise a ticket to duckdb to fix the rank function to match what the documentation says
- Temporally implement a rank evaluation that follows the VTL Reference Manual, focusing on the results and also ensuring the performance is similar

**Comment by javihern98** [comment]
Hi @noahboerger, we tested it and the current implementation is aligned with the expected result.

Your output is based on the fact that there is no partition involved, but the VTL Reference Manual 2.1 states that:

![image](https://github.com/user-attachments/assets/8149afbe-f52b-4de0-8d2c-6347877c8faa)

Therefore, we cannot achieve the desired result with the current VTL specification for Analytic invocation.

**Comment by javihern98** [comment]
Regarding the unhandled exception, we found the bug and solved it (we were not checking properly if the operand Dataset has no measures). The issue has been fixed and a test has been added.

**Comment by noahboerger** [comment]
Hi @javihern98,
Thank you very much for the explanation!

I still believe it should be possible to apply the rank function (and other analytic operators) easily on non-partitioned datasets. However, as you pointed out, your implementation follows the current specification. Therefore, I will open an issue in the task force repository regarding this matter.

Thanks again for your quick support!

**Comment by javihern98** [comment]
Bug has been solved and tests have been added, closing this issue on #40
